### PR TITLE
feat: .tsx extension support

### PR DESCRIPTION
**Pull request by jason-ha**
Detect .tsx files and update paths to .js

### CODE REVIEW

**Comment by bennycode** [comment]
That's another great addition! Let's also add support for `.cts` ([Module formats](https://www.typescriptlang.org/docs/handbook/modules/reference.html#module-format-detection)). 😀

**Comment by bennycode** [comment]
Thinking of it again... `cts` actually indicates that the module format should be CommonJS, so we better not touch it with ts2esm. Whereas `mts` is ESM, so there we can ensure that imports are using this new module syntax. I will add this one myself after merging your PR. 👍

**Comment by bennycode** [comment]
@jason-ha should this important `import App from "./components/app"` become `import App from "./components/app.jsx"` or `import App from "./components/app.js"` when using ESM?

**Comment by jason-ha** [comment]
> @jason-ha should this important `import App from "./components/app"` become `import App from "./components/app.jsx"` or `import App from "./components/app.js"` when using ESM?

It should be `.js` from my experience. I have limited React experience, but from what I understand any `.jsx` files should be transformed to `.js` files. At least in repo I am working with, `.tsx` files become `.js` files.

**Pull request merged**
